[package]
name = "emu8"
version = "0.1.0"
authors = ["rhys <rhysormond@gmail.com>"]
edition = "2018"

[dependencies]
chip8 = { version = "0.1.0", path = "chip8" }
clap = "3.0.0-beta.2"

[workspace]
members = ["chip8", "core", "display"]

